In [2]:
import pandas as pd
import numpy as np

In [5]:
 data=[{"Area":500,"Bedrooms":2,"Age":10,"Price":350000}]
 data.append({"Area":600,"Bedrooms":3,"Age":15,"Price":450000})

In [8]:
for i in range(5):
  area=int(input("Enter area:"))
  bedroom=int(input("Enter bedrooms:"))
  age=int(input("Enter age:"))
  price=int(input("Enter price:"))
  data.append({"Area":area,"Bedrooms":bedroom,"Age":age,"Price":price})

Enter area:500
Enter bedrooms:3
Enter age:10
Enter price:350000
Enter area:550
Enter bedrooms:3
Enter age:12
Enter price:4000000
Enter area:600
Enter bedrooms:4
Enter age:14
Enter price:550000
Enter area:450
Enter bedrooms:4
Enter age:13
Enter price:345000
Enter area:600
Enter bedrooms:5
Enter age:15
Enter price:540000

In [9]:
df=pd.DataFrame(data)

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [20]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [35]:
import random

In [57]:
import pandas as pd # Ensure pandas is imported if this cell is run independently
import random

for i in range(3):
  area=random.randint(1000,10000)
  bedroom=random.randint(1,5)
  age=random.randint(1,50)
  price=random.randint(100000,1000000)

In [41]:
data

    Area  Bedrooms  Age    Price
0    500         2   10   350000
1    600         3   15   450000
2    500         3   10   350000
3    550         3   12  4000000
4    600         4   14   550000
..   ...       ...  ...      ...
58  3664         1    1   160088
59  3987         4   28   820267
60  3966         3   10   320549
61  9873         1   26   370883
62  5302         2   42   985032

[63 rows x 4 columns]

from matplotlib import pyplot as plt
data['Area'].plot(kind='hist', bins=20, title='Area')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Bedrooms'].plot(kind='hist', bins=20, title='Bedrooms')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Area', y='Bedrooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Bedrooms', y='Age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Age', y='Price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Area'].plot(kind='line', figsize=(8, 4), title='Area')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Bedrooms'].plot(kind='line', figsize=(8, 4), title='Bedrooms')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

In [70]:
print(data)

    Area  Bedrooms  Age    Price
0    500         2   10   350000
1    600         3   15   450000
2    500         3   10   350000
3    550         3   12  4000000
4    600         4   14   550000
..   ...       ...  ...      ...
58  3664         1    1   160088
59  3987         4   28   820267
60  3966         3   10   320549
61  9873         1   26   370883
62  5302         2   42   985032

[63 rows x 4 columns]

In [69]:
data

    Area  Bedrooms  Age    Price
0    500         2   10   350000
1    600         3   15   450000
2    500         3   10   350000
3    550         3   12  4000000
4    600         4   14   550000
..   ...       ...  ...      ...
58  3664         1    1   160088
59  3987         4   28   820267
60  3966         3   10   320549
61  9873         1   26   370883
62  5302         2   42   985032

[63 rows x 4 columns]

In [71]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [72]:
df=pd.DataFrame(data)

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
import pandas as pd
df=pd.DataFrame(data)
df.to_csv("/content/drive/MyDrive/MSME Training/house_price.ipynb",index=False)

In [17]:
data=pd.read_csv("/content/drive/MyDrive/MSME Training/house_price.ipynb")

In [74]:
x=df.drop("Price",axis=1) #feature
y=data["Price"] #target

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [76]:
x_test

    Area  Bedrooms  Age
5    450         4   13
47  7217         4    2
58  3664         1    1
24  8915         3   11
0    500         2   10
8   1886         4   34
19  7704         4    7
23  9342         4   29
38  7086         5    5
52  1924         3   17
25  2431         4   29
3    550         3   12
16  6473         1   47

In [77]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [50]:
le=LinearRegression()
lr=LogisticRegression()

In [78]:
le.fit(x_train,y_train)

LinearRegression()

In [79]:
lr.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [80]:
x_test.shape

(13, 3)

In [81]:
le_predict=le.predict(x_test)

In [82]:
from sklearn.metrics import accuracy_score, mean_squared_error, precision_score, recall_score, f1_score

In [86]:
from numpy._core.fromnumeric import mean
mean_squared_error(y_test,le_predict)

1020611308465.4692

In [89]:
print("My house Price is: ",le_predict)

My house Price is:  [527483.71658315 490758.29087166 551074.12007583 505557.80876802
 555746.38542242 536896.52155728 492385.89946936 501681.92489761
 478181.24428003 539543.52996586 530905.09932745 541666.60227096
 573115.63671806]

In [90]:
x_test.shape

(13, 3)

In [84]:
from sklearn.linear_model import LogisticRegression

# Re-initialize and re-fit lr to ensure its predict method is not corrupted
lr = LogisticRegression()
lr.fit(x_train, y_train)

# Now perform the prediction
lr_predict=lr.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(